name: Metrics
on:
  # Update daily
  # https://crontab.guru/#0_0_*_*_*
  schedule: [{ cron: "0 0 * * *" }]
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Seoul

          # https://github.com/lowlighter/metrics/tree/latest/source/plugins/isocalendar
          plugin_isocalendar: yes

          # https://github.com/lowlighter/metrics/tree/latest/source/plugins/languages
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

          # https://github.com/lowlighter/metrics/tree/latest/source/plugins/introduction
          plugin_introduction: yes
          # plugin_introduction_title: no

          # https://github.com/lowlighter/metrics/tree/latest/source/plugins/habits
          plugin_habits: yes
          plugin_habits_from: 150
          plugin_habits_charts: yes

          # https://github.com/lowlighter/metrics/tree/latest/source/plugins/licenses
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes

          # https://github.com/lowlighter/metrics/tree/latest/source/plugins/followup
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          # https://github.com/lowlighter/metrics/tree/latest/source/plugins/lines
          plugin_lines: yes

          # https://github.com/lowlighter/metrics/tree/latest/source/plugins/stargazers
          plugin_stargazers: yes

          # https://github.com/lowlighter/metrics/tree/latest/source/plugins/achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B

          # https://github.com/lowlighter/metrics/tree/latest/source/plugins/notable
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_repositories: yes

          base: activity, community, repositories, metadata
          config_twemoji: yes
          repositories: 500
          plugin_traffic: yes
          plugin_topics: yes
          plugin_topics_sort: stars # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0 # Disable limitations
